### ISSUE TITLE
CP search doesn't work

### ISSUE THREAD

**Issue by romainpoirier** [verbb/formie#679] opened 2021-12-08 13:27 UTC
**Steps to reproduce**
1. Create a form
2. Set a field named `Test`
3. Create a new submission, add `Lorem` in `Test`
4. Go to `/admin/formie/submissions/myFormHandle`, select default status, and search for `Lorem`: you don't get result

### Form settings
- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: Yes

**Additional info**
- Plugin version: 1.4.28
- Craft version: 3.7.23
- Multi-site: Yes

**Comment by engram-design** [comment] 2021-12-08 21:52
I feel like there must be something strange going on with your install (see https://github.com/verbb/formie/issues/674), or I'm clearly missing something with reproducing your setup.

Searching certainly works for me, testing with existing forms, and brand new forms

![image](https://user-images.githubusercontent.com/1221575/145290136-f15571dc-ac47-42cc-99ba-b7e1bd878de2.png)

![image](https://user-images.githubusercontent.com/1221575/145290162-51f748ea-7b26-40aa-a843-93586395c61b.png)

And to confirm, I can look in my `searchindex` table for the `elementId` of the submission, 

![image](https://user-images.githubusercontent.com/1221575/145290246-65e4a21f-2753-41c7-bf87-362593eeba67.png)

Wondering if you can check in your `searchindex` table?

**Comment by romainpoirier** [comment] 2021-12-14 14:05
Thank you for investigating. But... I am unable to replicate it anymore for submissions submitted from a newly created form 🙈.. Maybe something has been fix during the last updates.

However, the search is still missing old and new submissions from previously created forms. I had to run manually `./craft resave/formie-forms` + `./craft resave/formie-submissions` to get them, and finally find them in the `searchindex` table.

For these older forms, maybe something is blocking the indexation, that's why it has to be done manually.

**Comment by engram-design** [comment] 2021-12-14 19:40
Thanks for confirming, strange. I know submissions should've been re-indexed some time ago (when fields were added to the index https://github.com/verbb/formie/blob/craft-3/src/migrations/m201010_000000_resave_submissions.php), but that was ages ago.

Closing for the moment, but keeping an eye on it...

**Closed as completed by engram-design** 2021-12-14 19:40 UTC

**Comment by romainpoirier** [comment] 2021-12-15 08:34
Thank you. By the way, I forgot to add: while index is now working for old and new submissions from old and new forms, I see that incomplete submissions are still not indexed in both cases, so they can't be searched from the CP: is it the expected behaviour?

**Comment by engram-design** [comment] 2021-12-15 10:39
Should be fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.5.2",
  "...": "..."
}
```

Then run `composer update`.

**Comment by romainpoirier** [comment] 2021-12-15 11:00
Thank you. But unfortunately I don't see any change for incomplete submissions, even after processing `./craft resave/formie-forms` + `./craft resave/formie-submissions` after updating.

**Comment by engram-design** [comment] 2021-12-16 00:21
I will say the search indexing happens in a queue job, so ensure that your queue is being run.

Otherwise, the change was to include incomplete submissions in the `anyStatus()` param, which was preventing Craft from picking it up with search indexing here https://github.com/craftcms/cms/blob/6cdc1bbce254a38c96a430938ff4995bd4dca942/src/queue/jobs/UpdateSearchIndex.php#L49-L55

Through this, it _should_ be picking up the elements to index.

**Comment by romainpoirier** [comment] 2021-12-16 08:39
Thank you. Yep, my queues are running in my env. I also tried to force using `'runQueueAutomatically' => true` and did a `./craft queue/run`. But even after this, my incomplete submissions are not still searchable.

**Comment by engram-design** [comment] 2021-12-16 09:40
Don't suppose you'd be up to sending your database to `web at verbb.io` so I can check your setup and what's different to mine?

**Comment by romainpoirier** [comment] 2022-01-14 12:48
Sorry for the late reply 🙈.  As I can't replicate the issue anymore, I think we can close this one from now. Thank you.
