### ISSUE TITLE
Unable to populate repeater fields

### ISSUE THREAD

**Issue by joespiteri** [verbb/formie#1190] opened 2022-11-22 11:06 UTC
### Describe the bug

I'm attempting to populate a repeater field [as documented here](https://verbb.io/craft-plugins/formie/docs/template-guides/populating-forms#repeater). Despite being able to populate other field types, repeater fields remain empty.

### Steps to reproduce

1. Create repeater field with a plain text sub-field
2. Use populateFormValues to set field values
3. Render form

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

4.3.3

### Plugin version

2.0.18

### Multi-site?

No

### Form export 
```
{
    "handle": "populationTest",
    "settings": "{\"displayFormTitle\":false,\"displayCurrentPageTitle\":false,\"displayPageTabs\":false,\"displayPageProgress\":false,\"scrollToTop\":true,\"progressPosition\":\"end\",\"defaultLabelPosition\":\"verbb\\\\formie\\\\positions\\\\AboveInput\",\"defaultInstructionsPosition\":\"verbb\\\\formie\\\\positions\\\\AboveInput\",\"submitMethod\":\"page-reload\",\"submitAction\":\"message\",\"submitActionTab\":null,\"submitActionUrl\":null,\"submitActionFormHide\":false,\"submitActionMessage\":\"[{\\\"type\\\":\\\"paragraph\\\",\\\"attrs\\\":{\\\"textAlign\\\":\\\"start\\\"},\\\"content\\\":[{\\\"type\\\":\\\"text\\\",\\\"text\\\":\\\"Submission saved.\\\"}]}]\",\"submitActionMessageTimeout\":null,\"submitActionMessagePosition\":\"top-form\",\"loadingIndicator\":null,\"loadingIndicatorText\":null,\"validationOnSubmit\":true,\"validationOnFocus\":false,\"errorMessage\":\"[{\\\"type\\\":\\\"paragraph\\\",\\\"attrs\\\":{\\\"textAlign\\\":\\\"start\\\"},\\\"content\\\":[{\\\"type\\\":\\\"text\\\",\\\"text\\\":\\\"Couldn\u2019t save submission due to errors.\\\"}]}]\",\"errorMessagePosition\":\"top-form\",\"requireUser\":false,\"requireUserMessage\":\"[{\\\"type\\\":\\\"paragraph\\\",\\\"attrs\\\":{\\\"textAlign\\\":\\\"start\\\"}}]\",\"scheduleForm\":false,\"scheduleFormStart\":null,\"scheduleFormEnd\":null,\"scheduleFormPendingMessage\":\"[{\\\"type\\\":\\\"paragraph\\\",\\\"attrs\\\":{\\\"textAlign\\\":\\\"start\\\"}}]\",\"scheduleFormExpiredMessage\":\"[{\\\"type\\\":\\\"paragraph\\\",\\\"attrs\\\":{\\\"textAlign\\\":\\\"start\\\"}}]\",\"limitSubmissions\":false,\"limitSubmissionsNumber\":null,\"limitSubmissionsType\":\"total\",\"limitSubmissionsMessage\":\"[{\\\"type\\\":\\\"paragraph\\\",\\\"attrs\\\":{\\\"textAlign\\\":\\\"start\\\"}}]\",\"integrations\":{\"recaptcha\":{\"enabled\":\"1\",\"showAllPages\":\"\"},\"hcaptcha\":{\"enabled\":\"1\",\"showAllPages\":\"\"},\"duplicate\":{\"enabled\":\"1\",\"showAllPages\":\"\"},\"honeypot\":{\"enabled\":\"1\",\"showAllPages\":\"\"},\"javascript\":{\"enabled\":\"1\",\"showAllPages\":\"\"}},\"submissionTitleFormat\":\"{timestamp}\",\"collectIp\":false,\"collectUser\":false,\"dataRetention\":null,\"dataRetentionValue\":null,\"fileUploadsAction\":null,\"redirectUrl\":null,\"defaultEmailTemplateId\":null,\"disableCaptchas\":false}",
    "submitActionEntryId": null,
    "submitActionEntrySiteId": null,
    "defaultStatusId": 1,
    "dataRetention": "forever",
    "dataRetentionValue": null,
    "userDeletedAction": "retain",
    "fileUploadsAction": "retain",
    "fieldLayoutId": 5,
    "title": "Population Test",
    "notifications": [],
    "pages": [
        {
            "settings": {
                "submitButtonLabel": "Submit",
                "backButtonLabel": "Back",
                "showBackButton": false,
                "saveButtonLabel": "Save",
                "showSaveButton": false,
                "saveButtonStyle": "link",
                "buttonsPosition": "left",
                "cssClasses": null,
                "containerAttributes": null,
                "inputAttributes": null,
                "enableNextButtonConditions": false,
                "nextButtonConditions": [],
                "enablePageConditions": false,
                "pageConditions": [],
                "enableJsEvents": false,
                "jsGtmEventOptions": []
            },
            "userCondition": null,
            "elementCondition": null,
            "label": "Page 1",
            "rows": [
                {
                    "fields": [
                        {
                            "label": "Test",
                            "handle": "test",
                            "type": "verbb\\formie\\fields\\formfields\\SingleLineText",
                            "settings": {
                                "instructions": null,
                                "required": false,
                                "limit": false,
                                "min": null,
                                "minType": "characters",
                                "max": null,
                                "maxType": "characters",
                                "matchField": null,
                                "placeholder": null,
                                "defaultValue": null,
                                "prePopulate": null,
                                "errorMessage": null,
                                "labelPosition": null,
                                "instructionsPosition": null,
                                "cssClasses": null,
                                "containerAttributes": null,
                                "inputAttributes": null,
                                "includeInEmail": true,
                                "enableConditions": false,
                                "conditions": null,
                                "enableContentEncryption": false,
                                "visibility": null,
                                "isNested": false
                            }
                        }
                    ]
                },
                {
                    "fields": [
                        {
                            "label": "Repeater",
                            "handle": "repeater",
                            "type": "verbb\\formie\\fields\\formfields\\Repeater",
                            "settings": {
                                "instructions": null,
                                "required": false,
                                "minRows": null,
                                "maxRows": null,
                                "addLabel": "Add another row",
                                "contentTable": "{{%fmc_33_repeater}}",
                                "matchField": null,
                                "placeholder": null,
                                "defaultValue": null,
                                "prePopulate": null,
                                "errorMessage": null,
                                "labelPosition": null,
                                "instructionsPosition": null,
                                "cssClasses": null,
                                "containerAttributes": null,
                                "inputAttributes": null,
                                "includeInEmail": true,
                                "enableConditions": false,
                                "conditions": null,
                                "enableContentEncryption": false,
                                "visibility": null,
                                "isNested": false
                            },
                            "rows": [
                                {
                                    "fields": [
                                        {
                                            "label": "Nested",
                                            "handle": "nested",
                                            "type": "verbb\\formie\\fields\\formfields\\SingleLineText",
                                            "settings": {
                                                "instructions": null,
                                                "required": false,
                                                "limit": false,
                                                "min": null,
                                                "minType": "characters",
                                                "max": null,
                                                "maxType": "characters",
                                                "matchField": null,
                                                "placeholder": null,
                                                "defaultValue": null,
                                                "prePopulate": null,
                                                "errorMessage": null,
                                                "labelPosition": null,
                                                "instructionsPosition": null,
                                                "cssClasses": null,
                                                "containerAttributes": null,
                                                "inputAttributes": null,
                                                "includeInEmail": true,
                                                "enableConditions": false,
                                                "conditions": null,
                                                "enableContentEncryption": false,
                                                "visibility": null,
                                                "isNested": false
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}
```

### Setting the values in the template

```
{% set form = craft.formie.forms.handle('populationTest').one() %}
    {% do craft.formie.populateFormValues(form, {
        test: 'Test',
        repeater: [
              {
                nested: 'Some Value',
              },
              {
                nested: 'Another Value',
              },
        ],
    }) %}
    {{ craft.formie.renderForm(form) }}
```

**Comment by engram-design** [comment] 2022-11-23 02:39
Fixed for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.18",
  "...": "..."
}
```

Then run `composer update`.

**Comment by joespiteri** [comment] 2022-11-23 09:50
Thanks for the quick fix

**Comment by ishetnogferre** [comment] 2023-01-12 12:02
I'm trying this in 2.0.20 with a repeater field _(handle: products)_ with following fields in it:
- a entries field _(handle: productId)_
- a number input _(handle: quantity)_

and with following code for trying to populate it:
```
{% do craft.formie.populateFormValues(formHandle, {
    projectName: "123eel",
    products: [
      {
        productId: 3975,
        quantity: 2
     },
     {
        productId: 16739,
        quantity: 1
     }
   ]
}) %}
```

All other fields of the same form, seem to be working with populating, just not the repeater one, am I doing something wrong?

**Comment by engram-design** [comment] 2023-01-13 03:09
One thing to note that it will by default only populate a completely empty submission, but you can [force it](https://verbb.io/craft-plugins/formie/docs/template-guides/populating-forms#forcing-values).

Otherwise, seems totally fine to me, and working on my end.

**Comment by ishetnogferre** [comment] 2023-01-13 10:09
For me it does populate the "project name" field with and without the **force** option set to true. The repeater stays unpopulated and looking like the default for some reason

<img width="785" alt="Screenshot 2023-01-13 at 11 06 40" src="https://user-images.githubusercontent.com/6649706/212293761-d319346e-1012-410e-b2c7-0b8aa0f10d97.png">

**Comment by engram-design** [comment] 2023-01-13 19:24
Hmmm, just re-created your form on my install, and that seems to populate correctly (entries would resolve correctly if I had matching element IDs).

<img width="742" alt="image" src="https://user-images.githubusercontent.com/1221575/212401843-1692db32-4352-4baa-b479-b0634962d5cf.png">

**Comment by ishetnogferre** [comment] 2023-01-14 08:17
Hmm.. I'm gonna try again with a new form, see if that works.

Also, for this method I don't need to add anything for the "Pre-Populate Value" option, right?

<img width="661" alt="Screenshot 2023-01-14 at 09 16 30" src="https://user-images.githubusercontent.com/6649706/212463020-c1fd29a6-4bb1-4c6f-adfe-9050cbf9b013.png">

**Comment by engram-design** [comment] 2023-01-14 12:12
Nope, that's for populating via a query string value. And yeah, if you can try to isolate it, however you can to it's most minimal, that's be great.

You can also send through a support request via Formie > Settings > Get Support - which will send me through your form data just in case that's different to my end in whatever way.

Is there anything worth mentioning about your front-end setup, or environment?

**Comment by ishetnogferre** [comment] 2023-01-14 13:09
Made a form with first just a number input and then just an entries field to try and see if I did anything wrong with the input and those worked. Then added the repeater again as described above, still nothing coming through, I'm afraid.

Gonna try some more debugging by using the dump function here and there. I also just sent you the data via the support form. As for setup, it's just a quite standard Craft CMS setup with Laravel Valet (there's a custom module with just action URLs but also turned everything off there and made no difference).

**Comment by engram-design** [comment] 2023-01-14 20:44
Thanks for sending that through - looks all okay on my end too. I'll keep at it!

```twig
{% do craft.formie.populateFormValues(form, {
    productId: [10733],
    products: [
        {
            productId: [11934],
        },
        {
            productId: [11920],
        },
    ],
}) %}
```

<img width="742" alt="image" src="https://user-images.githubusercontent.com/1221575/212495963-4df5f6a7-4715-42c5-80cf-3e4f33312360.png">

**Comment by ishetnogferre** [comment] 2023-01-16 09:24
So things I've tried today:
- I uninstalled and reinstalled the plugin 
- Installed on a new fresh Craft install with just 1 entry and the form field
- Also checked if Safari or Firefox made a difference instead of using Chrome

But form still remains empty:
<img width="398" alt="Screenshot 2023-01-16 at 10 20 15" src="https://user-images.githubusercontent.com/6649706/212642275-0d6466e8-86db-4c01-9f26-b1546bfd8779.png">


Here's the complete code how I'm getting and rendering the form:
```
{# Get the form #}
{% set handle = item.form.collect().one() %}
{% set form = craft.formie.forms({ handle: handle }).one() %}

{# Populate the form #}
{% do craft.formie.populateFormValues(form, {
  products: [
    {
      productId: [17],
    },
  ],
}) %}

{# Render the form #}
<div class="c-form">
  {{- craft.formie.renderForm(handle) -}}
</div>
```

Is there any other dump or logs I can provide, where we can check?

**Comment by engram-design** [comment] 2023-01-18 02:10
Would you mind sending over that test project to `support at verbb.io` for me to test? I've spun up a new site as well.

If you can include your database and entire site files, hopefully that'll ensure I can replicate this!

**Comment by ishetnogferre** [comment] 2023-01-18 08:30
@engram-design alright, I've sent over the test project

**Comment by engram-design** [comment] 2023-01-19 02:52
Thanks for that, that's certainly helped! Fixed for the next release. To get this early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-4 as 2.0.20",
  "...": "..."
}
```

Then run `composer update`.

**Comment by ishetnogferre** [comment] 2023-01-19 08:38
Almost 😅
Now got a "array to string" error with following code:

```{% do craft.formie.populateFormValues(handle, {
    projectName: "123eel",
    products: [
      {
        productId: [3975],
     },
     {
        productId: [16739],
     }
   ]
}, true) %}
```

```yii\base\ErrorException: Array to string conversion in /Users/ferrelambert/Code/2tec2/vendor/craftcms/cms/src/helpers/Db.php:566
Stack trace:
#0 /Users/ferrelambert/Code/2tec2/vendor/craftcms/cms/src/web/ErrorHandler.php(79): yii\base\ErrorHandler->handleError(2, 'Array to string...', '/Users/ferrelam...', 566)
#1 /Users/ferrelambert/Code/2tec2/vendor/craftcms/cms/src/helpers/Db.php(566): craft\web\ErrorHandler->handleError(2, 'Array to string...', '/Users/ferrelam...', 566)
#2 /Users/ferrelambert/Code/2tec2/vendor/craftcms/cms/src/helpers/Db.php(817): craft\helpers\Db::parseParam('elements.id', Array, '=', false, 'integer')
#3 /Users/ferrelambert/Code/2tec2/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1330): craft\helpers\Db::parseNumericParam('elements.id', Array)
#4 /Users/ferrelambert/Code/2tec2/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#5 /Users/ferrelambert/Code/2tec2/vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build(Object(craft\elements\db\EntryQuery))
#6 /Users/ferrelambert/Code/2tec2/vendor/yiisoft/yii2/db/Query.php(249): yii\db\Query->createCommand(Object(craft\db\Connection))
#7 /Users/ferrelambert/Code/2tec2/vendor/craftcms/cms/src/db/Query.php(248): yii\db\Query->all(NULL)
#8 /Users/ferrelambert/Code/2tec2/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1492): craft\db\Query->all(NULL)
#9 /Users/ferrelambert/Code/2tec2/vendor/verbb/formie/src/base/RelationFieldTrait.php(145): craft\elements\db\ElementQuery->all()
#10 /Users/ferrelambert/Code/2tec2/vendor/verbb/formie/src/fields/formfields/Entries.php(128): verbb\formie\fields\formfields\Entries->getDefaultValueQuery()
#11 /Users/ferrelambert/Code/2tec2/vendor/verbb/formie/src/base/FormFieldTrait.php(587): verbb\formie\fields\formfields\Entries->getDefaultValue('')
#12 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/Extension/CoreExtension.php(1607): verbb\formie\fields\formfields\Entries->getFieldValue(NULL)
#13 /Users/ferrelambert/Code/2tec2/vendor/craftcms/cms/src/helpers/Template.php(110): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(verbb\formie\fields\formfields\Entries), 'getFieldValue', Array, 'method', false, false)
#14 /Users/ferrelambert/Code/2tec2/storage/runtime/compiled_templates/7f/7fe1b21f7022057fd9c1954439619ec6.php(44): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(verbb\formie\fields\formfields\Entries), 'getFieldValue', Array, 'method')
#15 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/Template.php(394): __TwigTemplate_9b6b9895287cfedc5b5f3353f8dff16b->doDisplay(Array, Array)
#16 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#17 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#18 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#19 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render(Array)
#20 /Users/ferrelambert/Code/2tec2/vendor/craftcms/cms/src/web/View.php(451): Twig\Environment->render('formie/_special...', Array)
#21 /Users/ferrelambert/Code/2tec2/vendor/verbb/formie/src/elements/Form.php(1326): craft\web\View->renderTemplate('formie/_special...', Array, 'cp')
#22 /Users/ferrelambert/Code/2tec2/vendor/verbb/formie/src/services/Rendering.php(208): verbb\formie\elements\Form->renderTemplate(Array, Array)
#23 /Users/ferrelambert/Code/2tec2/vendor/verbb/formie/src/variables/Formie.php(149): verbb\formie\services\Rendering->renderField(Object(verbb\formie\elements\Form), Object(verbb\formie\fields\formfields\Entries), Array)
#24 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/Extension/CoreExtension.php(1607): verbb\formie\variables\Formie->renderField(Object(verbb\formie\elements\Form), Object(verbb\formie\fields\formfields\Entries), Array)
#25 /Users/ferrelambert/Code/2tec2/vendor/craftcms/cms/src/helpers/Template.php(110): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(verbb\formie\variables\Formie), 'renderField', Array, 'method', false, false)
#26 /Users/ferrelambert/Code/2tec2/storage/runtime/compiled_templates/30/30b5efc764d4ab682e1a9ffcf6ad11d1.php(81): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(verbb\formie\variables\Formie), 'renderField', Array, 'method')
#27 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/Template.php(394): __TwigTemplate_4e6a11935bd428dd73ac889af5ba6aa2->doDisplay(Array, Array)
#28 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#29 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#30 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#31 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render(Array)
#32 /Users/ferrelambert/Code/2tec2/vendor/craftcms/cms/src/web/View.php(451): Twig\Environment->render('formie/_special...', Array)
#33 /Users/ferrelambert/Code/2tec2/vendor/verbb/formie/src/elements/Form.php(1326): craft\web\View->renderTemplate('formie/_special...', Array, 'cp')
#34 /Users/ferrelambert/Code/2tec2/vendor/verbb/formie/src/services/Rendering.php(157): verbb\formie\elements\Form->renderTemplate(Array, Array)
#35 /Users/ferrelambert/Code/2tec2/vendor/verbb/formie/src/variables/Formie.php(132): verbb\formie\services\Rendering->renderPage(Object(verbb\formie\elements\Form), Object(verbb\formie\models\FieldLayoutPage), Array)
#36 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/Extension/CoreExtension.php(1607): verbb\formie\variables\Formie->renderPage(Object(verbb\formie\elements\Form), Object(verbb\formie\models\FieldLayoutPage), Array)
#37 /Users/ferrelambert/Code/2tec2/vendor/craftcms/cms/src/helpers/Template.php(110): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(verbb\formie\variables\Formie), 'renderPage', Array, 'method', false, false)
#38 /Users/ferrelambert/Code/2tec2/storage/runtime/compiled_templates/7e/7e95f6f1d4649629792db2a8a3000e70.php(237): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(verbb\formie\variables\Formie), 'renderPage', Array, 'method')
#39 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/Template.php(394): __TwigTemplate_506a74d04d084a4c2aad042c0dc69dbd->doDisplay(Array, Array)
#40 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#41 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#42 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#43 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render(Array)
#44 /Users/ferrelambert/Code/2tec2/vendor/craftcms/cms/src/web/View.php(451): Twig\Environment->render('formie/_special...', Array)
#45 /Users/ferrelambert/Code/2tec2/vendor/verbb/formie/src/elements/Form.php(1326): craft\web\View->renderTemplate('formie/_special...', Array, 'cp')
#46 /Users/ferrelambert/Code/2tec2/vendor/verbb/formie/src/services/Rendering.php(90): verbb\formie\elements\Form->renderTemplate(Array, Array)
#47 /Users/ferrelambert/Code/2tec2/vendor/verbb/formie/src/variables/Formie.php(114): verbb\formie\services\Rendering->renderForm(Object(verbb\formie\elements\Form), Array)
#48 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/Extension/CoreExtension.php(1607): verbb\formie\variables\Formie->renderForm('orderForm', Array)
#49 /Users/ferrelambert/Code/2tec2/vendor/craftcms/cms/src/helpers/Template.php(110): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(verbb\formie\variables\Formie), 'renderForm', Array, 'method', false, false)
#50 /Users/ferrelambert/Code/2tec2/storage/runtime/compiled_templates/bb/bb86a1594a3c184cc906876658113099.php(66): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(verbb\formie\variables\Formie), 'renderForm', Array, 'method')
#51 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/Template.php(394): __TwigTemplate_e4d7d18f26653a3921f028604e7ff06e->doDisplay(Array, Array)
#52 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#53 /Users/ferrelambert/Code/2tec2/storage/runtime/compiled_templates/e7/e7592bbe2b9b8b794d4cd9c5bd5ed08a.php(83): Twig\Template->display(Array)
#54 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/Template.php(171): __TwigTemplate_04439a0b81efa2d3f0433704462086ec->block_before_builder(Array, Array)
#55 /Users/ferrelambert/Code/2tec2/storage/runtime/compiled_templates/5b/5ba04120f5f8ef10938342a4cbcda08e.php(61): Twig\Template->displayBlock('before_builder', Array, Array)
#56 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/Template.php(171): __TwigTemplate_6525c07fe81d66132436c835603a3b96->block_content(Array, Array)
#57 /Users/ferrelambert/Code/2tec2/storage/runtime/compiled_templates/5b/5ba04120f5f8ef10938342a4cbcda08e.php(51): Twig\Template->displayBlock('content', Array, Array)
#58 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/Template.php(394): __TwigTemplate_6525c07fe81d66132436c835603a3b96->doDisplay(Array, Array)
#59 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#60 /Users/ferrelambert/Code/2tec2/storage/runtime/compiled_templates/e7/e7592bbe2b9b8b794d4cd9c5bd5ed08a.php(65): Twig\Template->display(Array, Array)
#61 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/Template.php(394): __TwigTemplate_04439a0b81efa2d3f0433704462086ec->doDisplay(Array, Array)
#62 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#63 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/TemplateWrapper.php(47): Twig\Template->display(Array, Array)
#64 /Users/ferrelambert/Code/2tec2/storage/runtime/compiled_templates/76/76d1790e7f3c1822b0a77ff8b98904b6.php(49): Twig\TemplateWrapper->display(Array)
#65 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/Template.php(394): __TwigTemplate_9dd3517a0ec07bbafdb400fe14a4069e->doDisplay(Array, Array)
#66 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#67 /Users/ferrelambert/Code/2tec2/storage/runtime/compiled_templates/c8/c84028dbb125a9052812d06cae7cdabd.php(297): Twig\Template->display(Array)
#68 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/Template.php(171): __TwigTemplate_4e954a43d765814eb09202a5a46e1536->block_content(Array, Array)
#69 /Users/ferrelambert/Code/2tec2/storage/runtime/compiled_templates/b6/b6143c79ca283b818b5a56c4c0b704ba.php(95): Twig\Template->displayBlock('content', Array, Array)
#70 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/Template.php(394): __TwigTemplate_f41c43013612b55c6a90fbd7d4643ec1->doDisplay(Array, Array)
#71 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#72 /Users/ferrelambert/Code/2tec2/storage/runtime/compiled_templates/c8/c84028dbb125a9052812d06cae7cdabd.php(156): Twig\Template->display(Array, Array)
#73 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/Template.php(394): __TwigTemplate_4e954a43d765814eb09202a5a46e1536->doDisplay(Array, Array)
#74 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#75 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#76 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#77 /Users/ferrelambert/Code/2tec2/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render(Array)
#78 /Users/ferrelambert/Code/2tec2/vendor/craftcms/cms/src/web/View.php(451): Twig\Environment->render('_resolvers/page...', Array)
#79 /Users/ferrelambert/Code/2tec2/vendor/craftcms/cms/src/web/View.php(504): craft\web\View->renderTemplate('_resolvers/page...', Array)
#80 /Users/ferrelambert/Code/2tec2/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(56): craft\web\View->renderPageTemplate('_resolvers/page...', Array, 'site')
#81 /Users/ferrelambert/Code/2tec2/vendor/yiisoft/yii2/web/Response.php(1098): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#82 /Users/ferrelambert/Code/2tec2/vendor/craftcms/cms/src/web/Response.php(286): yii\web\Response->prepare()
#83 /Users/ferrelambert/Code/2tec2/vendor/yiisoft/yii2/web/Response.php(339): craft\web\Response->prepare()
#84 /Users/ferrelambert/Code/2tec2/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#85 /Users/ferrelambert/Code/2tec2/web/index.php(15): yii\base\Application->run()
#86 /Users/ferrelambert/.composer/vendor/laravel/valet/server.php(235): require('/Users/ferrelam...')
#87 {main}`

**Comment by engram-design** [comment] 2023-01-19 11:59
Can't seem to replicate that on your sample install, sorry! Anything else unique to your setup, template overrides or anything? Can you replicate it on your sample install

**Comment by ishetnogferre** [comment] 2023-01-19 19:06
Found it! Was a mistake on my part, had another entries field hidden in a different component (for another test).

It works now, thanks a bunch! 🙏

**Comment by engram-design** [comment] 2023-01-29 21:12
Fixed in [2.0.21](https://github.com/verbb/formie/releases/tag/2.0.21)

**Comment by scottwakefield** [comment] 2023-11-30 23:09
Hey, @engram-design!

I've been experiencing the same behaviour on a Craft 3.9.6 project, running Formie 1.6.35.

After I found this Issue, I manually applied the change in https://github.com/verbb/formie/commit/cbbf0d8a229b18bf22503a2cc8cf68e84517c357 to 1.6.35 locally and it _seems_ to fix the issue.

The strange thing is, we have ~10 websites all built using the same boilerplate—they're all almost identical—and we only had this particular issue with one of them. I can't seem to pin down why 🤷🏻‍♂️

Anyway, I wondered whether this fix could be applied to v1, too?

**Comment by engram-design** [comment] 2023-12-01 03:10
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-3 as 1.6.35"`.

**Comment by engram-design** [comment] 2023-12-12 10:23
Fixed in [1.6.36](https://github.com/verbb/formie/releases/tag/1.6.36)

**Closed as completed by engram-design** 2023-12-12 10:23 UTC

**Comment by jessedobbelaere** [comment] 2023-12-20 00:43
Hi @engram-design I'm experiencing the same issue again in the latest Formie (`2.0.44.1`). I'm wondering if there's a regression that slipped in one of the past releases since v2.0.21? Should I open a new issue?

I created a simple form with a repeater field with an entries field inside. I run:

```
{% set form = craft.formie.forms({ handle: 'testForm' }).one() %}
{% do craft.formie.populateFormValues(form, {
    repeaterField: [
        {
            entriesField: [2125],
            quantityField: 3,
        },
    ],
    entriesFieldWithoutRepeater: [2125],
}) %}
{{ craft.formie.renderForm(form) }}
```

The quantity field is getting prepopulated, the entries field isn't. When I make an entries field without repeater, it gets filled in properly. Thanks for checking!

![Screenshot 2023-12-20 at 01 24 21@2x](https://github.com/verbb/formie/assets/1352979/069ac25c-4d41-431e-810c-f56359c4367e)

**Comment by engram-design** [comment] 2023-12-20 02:23
Hmm, that seems to be working for me! 
<img width="736" alt="image" src="https://github.com/verbb/formie/assets/1221575/531db9db-f4c3-444c-9ce1-50307fd64bda">
