### ISSUE TITLE
Updating to formie 1.2.28 composer error, Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by ryguy2407** [verbb/formie#224] opened 2020-11-24 05:07 UTC
I've run composer update and then craft update all and I get the following error from composer

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for verbb/formie 1.2.28 -> satisfiable by verbb/formie[1.2.28].
    - Conclusion: remove fzaninotto/faker v1.9.1
    - Conclusion: don't install fzaninotto/faker v1.9.1
    - verbb/formie 1.2.28 requires fakerphp/faker ^1.9 -> satisfiable by fakerphp/faker[v1.12.0, v1.11.0, v1.10.1, v1.10.0, v1.9.1].
    - fakerphp/faker v1.12.0 conflicts with fzaninotto/faker[v1.9.1].
    - fakerphp/faker v1.11.0 conflicts with fzaninotto/faker[v1.9.1].
    - fakerphp/faker v1.10.1 conflicts with fzaninotto/faker[v1.9.1].
    - fakerphp/faker v1.10.0 conflicts with fzaninotto/faker[v1.9.1].
    - don't install fakerphp/faker v1.9.1|don't install fzaninotto/faker v1.9.1
    - Installation request for fzaninotto/faker (locked at v1.9.1) -> satisfiable by fzaninotto/faker[v1.9.1].

I tried removing fzaninotto/faker by running composer remove fzaninotto/faker but since it isn't required in my composer.json file, it doesn't get removed.

Not sure if I'm doing something wrong here. Generally a composer update seems to fix any dependency conflict issues I've had in the past.

Thanks!

**Comment by engram-design** [comment] 2020-11-24 07:18
Duplicate of https://github.com/verbb/formie/issues/223

**Closed as completed by engram-design** 2020-11-24 07:18 UTC
