### ISSUE TITLE
Custom validator rule not triggering on dropdown field

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/formie#1268] opened 2023-01-29 21:48 UTC
### Describe the bug

I'm not sure if this is a bug or more to do with the required validator itself.

For a form I want to make a dropdown field required but only when another field (that also happens to be a dropdown) is a specific option. I figured I can use the required validator with when to check the data in the model for the validation rule to trigger.

```php
$event->rules[] = [['field:dropdownfield'], 'required', 'when' => function($model) {
    return $model->anotherDropDownField->label === 'Example';
}];
```

What I'm finding is no validation error is raised, but I've checked to make sure the rule is being added and it is.

Thinking it could be due to the default "Select an option" not being null but an empty string, I tried:

```php
$event->rules[] = [['field:dropdownfield'], 'required', 'when' => function($model) {
    return $model->dropdownfield === '' && $model->anotherDropDownField->label === 'Example';
}];
```

This however still doesn't trigger a validation message when submitting.

The condition 100% returns true when dumping, so it's not that. To sanity check, I changed `field:dropdownfield` to a multi-line text field and tested again and this does raise the validation error on the text field.

So can only conclude that it's something specific with dropdown fields. I am wondering if it's because of the fact a value might exist, if it's an empty string rather than null?

The value of `field:dropdownfield` is an empty string as it's the "Select an option" value which is default. I want that to raise a validation error to be treated as not a valid option.

### Steps to reproduce

1. Add custom validation rule to dropdown field using the required validator with when to return true on a field condition being met
2. Expect the validation error to be raised on the dropdown field, but nothing is

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

3.7.63.1

### Plugin version

1.6.21

### Multi-site?

No

**Comment by engram-design** [comment] 2023-01-29 22:46
FYI, conditions are supported with required fields, if that helps. A field marked as required, but hidden through conditions won't throw a validation error.

Didn't actually realise this was an issue until diving into the validator specifics. It's not really a bug, but also probably not going to be addressed due to the behaviour changing for custom validators in Formie 2/Craft 4.

The issue is that Craft's normal required validator will add a `isEmpty` param to the validator. This would resolve to the field's `isValueEmpty` method. That's not an automatic thing, and the default behaviour of Yii's required validator will simply look to see if `$element->dropdownField` has a value. Which technically it _does_ the value being an empty `SingleOptionFieldData` model, which is the reason fields can define what's an empty value or not.

So, it's a matter of adding that method call to the `isEmpty` param when registering your event. This only effects complicated fields, which is why it works just fine for simple text fields.

```php
$isEmpty = [$event->sender, 'field:dropdownfield'];

$event->rules[] = [['field:dropdownfield'], 'required', 'isEmpty' => $isEmpty, 'when' => function($model) {
    return $model->anotherDropDownField->label === 'Example';
}];
```

**Comment by jamesmacwhite** [comment] 2023-01-29 23:20
Thank you! That does explain the difference of behaviour compared to text fields.

This seems to work:

```PHP
$event->rules[] = [
	['field:whatTypeOfCourseAreYouInterestedIn'], 'required', 'isEmpty' => function ($options) {
            return empty($options->value);
	},
         'when' => function($model) {
	     return $model->youAreEnquiringAboutTheFollowing->label === 'General Course';
	}
];
```

I can now see that the value isn't in fact an empty string but an SingleOptionFieldData, until you specifically provide the value and then it works!

**Comment by engram-design** [comment] 2023-01-29 23:23
FYI, I'd still recommend using `$isEmpty = [$event->sender, 'field:dropdownfield'];` as that will end up resolving to [`isValueEmpty`](https://github.com/craftcms/cms/blob/ea55235e5a9677aa577f3a701dd4eaa04c2010b7/src/fields/BaseOptionsField.php#L402) which is defined by the field, rather than you having to add "is empty" logic.

**Comment by jamesmacwhite** [comment] 2023-01-29 23:30
I was unable to get that example to work for some reason

> Calling unknown method: verbb\formie\elements\Submission::field:whatTypeOfCourseAreYouInterestedIn()

I got an unknown method error, when I set the empty logic directly it was OK.

**Comment by engram-design** [comment] 2023-01-29 23:39
It should only throw an error if the field `whatTypeOfCourseAreYouInterestedIn` doesn't exist for that submission. But as you say, it's risky doing this anyway, because this code will run for all submissions on your site. Formie's internals filter out this error where you try to apply field validations on a field that might not exist on the element (submission). Craft's default behaviour is to throw an error like this.

**Closed as completed** 2023-02-20 07:21 UTC
