### ISSUE TITLE
Email notifications are not being sent when using GraphQL to submit a new form.

### ISSUE THREAD

**Issue by grndctrl** [verbb/formie#118] opened 2020-09-21 09:47 UTC
**Description**
Email notifications, either to client/user or admin, are not being sent when using GraphQL to submit a new form.
I'm trying to submit a form through NextJS, on a different domein. The submission is saved nicely as a new entry, but I receive no notification of it. In CraftCMS there are no pending jobs in the Queue manager either.

**Steps to reproduce**
1. Submit form through GraphQL

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: AJAX
- Client-side Validation: No
- Custom Form Templates: Yes, super simple test form

**Additional info**
- Plugin version: 1.2.14
- Craft version: 3.5.11.1
- Multi-site: No

**Additional context**
I'm using Apollo to handle my GraphQL.
Test emails send from the Email settings in Craft do work and I receive them.

**Comment by engram-design** [comment] 2020-09-21 09:49
Duplicate of https://github.com/verbb/formie/issues/116

**Closed as completed by engram-design** 2020-09-21 09:49 UTC
