### ISSUE TITLE
ModifyEmailFieldUniqueQueryEvent does not comply with psr-4 autoloading standard

### ISSUE THREAD

**Issue by bartdepotter** [verbb/formie#1674] opened 2024-01-02 20:17 UTC
### Describe the bug

The following error occurred on composer install:

`Class verbb\formie\events\ModifyEmailFieldUniqueQueryEvent located in ./vendor/verbb/formie/src/base/ModifyFieldUniqueQueryEvent.php does not comply with psr-4 autoloading standard. Skipping.`

### Steps to reproduce

 1. php craft update all
 2. composer install

### Form settings

- Multi-page form: Yes or No
- Submission Method: Ajax or Page Reload
- Client-side Validation: Yes or No
- Custom Form Templates: Yes or No

### Craft CMS version

Craft Pro 4.5.14

### Plugin version

2.1.1

### Multi-site?

No

### Additional context

Warning only shows after composer install.

**Comment by engram-design** [comment] 2024-01-02 20:24
Duplicate of https://github.com/verbb/formie/issues/1669

**Closed as completed by engram-design** 2024-01-02 20:24 UTC
