### ISSUE TITLE
Slack integration works if manually triggered in submission dashboard, but not automatically on form submission itself

### ISSUE THREAD

**Issue by toddpadwick** [verbb/formie#822] opened 2022-04-07 09:51 UTC
**Description**
Set up new slack integration. However, the slack integration is not triggering automatically as expected. Notification is only received if manually triggered in the CMS submission page.

We are hosting on Digital Ocean Pro stack which is a load balanced service, using workers to run the queue. I can confirm the worker works with all other queue events.
I checked the queue in the dashboard, and there is nothing in there pending or failed.

<img width="627" alt="Screenshot 2022-04-07 at 11 42 26" src="https://user-images.githubusercontent.com/36191462/162172148-58e9d75e-07e1-44f5-9364-187a5d6fbbee.png">

**Additional info**
- Plugin version:dev-craft-3 as 1.5.12
- Craft version:Craft Pro 3.7.37

**Comment by engram-design** [comment] 2022-04-07 11:19
That sounds like correct behaviour, due to integrations being added to the queue, and Craft's default handling of running the queue is only when visiting the control panel? But it does sound like you have the CLI setup to process the queue automatically. I don't see any reason how once the queue job is processed, the notification is sent to Slack.

So does the queue job get created? Or is it processed too fast to be able to tell?

And you mention:
> Notification is only received if manually triggered in the CMS submission page

Is that just _any_ CP page? Or are you finding it only does it on certain pages (which would be odd).

**Comment by toddpadwick** [comment] 2022-04-07 12:03
@engram-design  Surely it should work like all other notifications, that get sent as soon as a form is submitted? Otherwise, the client may not be aware of a contact form submission until they next log in to Craft which wouldn't make sense.

It seems to be processed too fast to be able to tell if its added to the queue.

What i meant by manually triggered, is by the drop down integration selector in an already received submission. Triggering the integration in this way results in the notification being sent to the slack channel as expected. But we don't receive anything before then.

<img width="272" alt="Screenshot 2022-04-07 at 14 00 46" src="https://user-images.githubusercontent.com/36191462/162194201-f0476a29-0735-4a34-86d1-0cc715c733e3.png">

**Comment by engram-design** [comment] 2022-04-07 22:03
Oh gotcha, yep so manually triggering the integration like that doesn't use the queue system at all, so in some ways in a good way to test there's not something wrong with your queue processing, or there's something wrong with the integration being run from the CLI vs a web request.

In your case, it seems like the latter, although I've been testing running the queue and triggering a Slack notification _just in case_ there's something different with Slack, but it all goes through.

Nothing in the logs (/storage/logs/formie.log or /storage/logs/queue.log)?

**Comment by toddpadwick** [comment] 2022-04-08 08:37
@engram-design I wonder then, if this is an issue with the plugin not playing ball with the load balanced system. I cannot see past logs, i can only see new ones when I tail them. There are no queue logs happening when a form is submitted. so it doesn't look like its even reaching the queue. Could it be related to this comment from Fortrabbit?  I expect it would be a similar case on any load balanced solution, whether on fortrabbit or custom set up on AWS.

> First guess into the blue: Somehow related to ephemeral storage with our Pro Stack. It won't work if some configuration is written to a file from the App. You can store state in the database or in Memcache, but not on the local file system.
> More on ephemeral storage:
> ﻿https://help.fortrabbit.com/app-pro#toc-ephemeral-storage
> Again, that is just a guess without understanding full context. I have leveled this case up.

**Comment by engram-design** [comment] 2022-04-09 02:58
I'll say my load balancing experience is limited, but the queue system is database-stored so I wouldn't have thought there be any difference. I imagine there's still a central install that controls things like the queue?

As a test, could you stop your queue processing (whatever form that looks for your setup), and create a form submission, and verify the queue job is created, and sitting in there pending? Click into the job to view details on it, then run the queue processing. It should automatically update the job without a need to refresh the page, and it should be completed, with the notification in Slack.

**Comment by toddpadwick** [comment] 2022-04-11 11:02
Hi @engram-design  i disabled the queue runner. However, when submitting a form, no job was added to the pending queue. So it seems the job doesn't actually get created.

**Comment by engram-design** [comment] 2022-04-11 11:16
Interesting. I assume you have "Use Queue for Integrations" enabled? Otherwise, integrations will circumvent the queue and be run as soon as the form is submitted.

Do your load balancers use a single database, or is it distributed?

I'll also assume there's nothing in your `/storage/logs/formie.log` file?

**Comment by toddpadwick** [comment] 2022-04-11 12:27
1. I haven't changed any settings (and have not created a formie.php file) so will be set to default. Should I?
2. I'm pretty sure its a single database. I'll double-check with Fortrabbit though.
3. There is no log file in the load balanced set up.

**Comment by engram-design** [comment] 2022-04-11 12:55
No need to change the defaults, the default will use the queue.

How is your queue processed on Fortrabbit? I imagine it's triggered through their CLI, and you'd have `runQueueAutomatically` set to `false` in your general.php config?

D'oh, of course you've told me plenty of times about the lack of log files. Are you able to tail it while making a submission?

**Comment by toddpadwick** [comment] 2022-04-11 13:28
1. Thats correct
2. we are using a worker non-stop-job running `craft queue/listen`. Same set up on all our sites on Fortrabbit. And as you guessed – we have `runQueueAutomatically` set to `false`.
3. Yes, when I tail logs this is what I get when submitting a form:
```
apache_access  184.153.25.99 - - [11/Apr/2022:13:24:44 +0000] "POST /graphql?p=graphql HTTP/1.1" 200 8385 "https://www.usrem.co/about-us" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"
apache_access  184.153.25.99 - - [11/Apr/2022:13:24:45 +0000] "POST /graphql?p=graphql HTTP/1.1" 200 12973 "https://www.usrem.co/about-us" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0"
apache_access  68.161.194.12 - - [11/Apr/2022:13:24:48 +0000] "GET /index.php/admin/actions/users/session-info?dontExtendSession=1 HTTP/1.1" 200 552 "https://cms.usrem.co/admin/plugin-store/categories/344" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"
apache_access  91.126.213.35 - - [11/Apr/2022:13:24:55 +0000] "GET /index.php/admin/actions/users/session-info?dontExtendSession=1 HTTP/1.1" 200 1108 "https://cms.usrem.co/admin/formie/settings/address-providers" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36"
worker         2022-04-11T13:25:35Z CTRL (default-queue): Start
apache_access  68.161.194.12 - - [11/Apr/2022:13:25:49 +0000] "GET /index.php/admin/actions/users/session-info?dontExtendSession=1 HTTP/1.1" 200 552 "https://cms.usrem.co/admin/plugin-store/categories/344" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"
apache_access  91.126.213.35 - - [11/Apr/2022:13:25:50 +0000] "OPTIONS /graphql?p=graphql HTTP/1.1" 200 325 "https://www.usrem.co/forms/contact-us" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36"
apache_access  91.126.213.35 - - [11/Apr/2022:13:25:50 +0000] "POST /graphql?p=graphql HTTP/1.1" 200 404 "https://www.usrem.co/forms/contact-us" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36"
apache_access  91.126.213.35 - - [11/Apr/2022:13:25:56 +0000] "GET /index.php/admin/actions/users/session-info?dontExtendSession=1 HTTP/1.1" 200 1021 "https://cms.usrem.co/admin/formie/settings/address-providers" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36"
worker         2022-04-11T13:26:14Z CTRL (default-queue): Start
```

**Comment by engram-design** [comment] 2022-04-11 13:40
Yep, so that's the apache logs, but not quite what we're after. But as there's no logs on the filesystem, I may need to look at other options to see what might be going wrong, as Formie's logs will usually give insight into the issue.

**Comment by toddpadwick** [comment] 2022-04-12 08:00
Spoke to Fortrabbit and they have access to historical logs internally. they found this:
```
2022-04-11 09:25:51 [-][-][-][info][formie] Submission marked as spam - “Failed Captcha “Recaptcha”: “{"success":false,"error-codes":["invalid-input-secret"]}”” - {"leadType":"Investor","name1":"{\"prefix\":null,\"firstName\":\"Todd\",\"middleName\":null,\"lastName\":\"Padwick\",\"name\":null,\"isMultiple\":null}","companyName":"test","role":"test","email":"test@functionandform.co.uk","phone":"{\"number\":null,\"country\":null,\"hasCountryCode\":false}","message":"Test","dataProtection":true}.
2022-04-11 09:25:50 [-][-][-][info][application] Request body: {"operationName":"FormMutation","query":"\n        mutation FormMutation($contactUs: String, $leadType: String, $name1: contactUs_name1_FormieNameInput, $companyName: String, $role: String, $email: String, $phone: String, $message: String, $dataProtection: String) {\n            save_contactUs_Submission(contactUs: $contactUs, leadType: $leadType, name1: $name1, companyName: $companyName, role: $role, email: $email, phone: $phone, message: $message, dataProtection: $dataProtection) {\n                id\n            }\n        }\n    ","variables":{"leadType":"Investor","name1":{"firstName":"Todd","lastName":"Padwick"},"companyName":"test","role":"test","email":"test@functionandform.co.uk","phone":"","message":"Test","dataProtection":"1"},"g-recaptcha-response":"---REMOVED---"}
```

I checked in submissions and I cannot find any spam emails despite the fact I have the 'save spam submissions' set to true. Do you know why that might be?

**Comment by engram-design** [comment] 2022-04-12 08:06
So that was my next suggestion was if these submissions were actually going through as spam, which it looks like they are. So there's no spam submission **at all**?

It looks like you're using mutations to trigger submissions, so I imagine this is a headless site? If that's the case, captchas won't work at all using mutations unless you're on [1.5.12](https://github.com/verbb/formie/issues/794) and if you include them in the mutation payload https://verbb.io/craft-plugins/formie/docs/developers/graphql#captchas

**Comment by toddpadwick** [comment] 2022-04-12 08:14
Ah turns out the recapcha thing was just a recent issue -whereby we transferred the domain to production but forgot to change the recaphca site from staging.usrem.co to www.usrem.co. Unfortunately the other issue remains. 

and yes, we are using the mutation payload which we've had working fine until the above oversight, which I've now rectified. Although, the fact that spam submissions are not being saved is still a minor problem. 

I have now got the recapcha working again, and submissions are being received in the admin, but still no slack notification.

**Comment by engram-design** [comment] 2022-04-12 08:33
That's certainly strange about the submissions not saving, as that would've help you diagnose this one (it would've shown the spam reason as a hint).

So submissions are going through successfully now (you can see them in the control panel), but integrations just not triggering? I will mention if you've been able to successfully connect to Slack via the integration settings on production - as well as refresh the Slack channels?

I'll likely spin up a Fortrabbit site when I'm able to, to diagnose this further, as I can't imagine I could get access to your production site.

**Comment by toddpadwick** [comment] 2022-04-12 09:13
Hi @engram-design 

- submissions are going through in CP, just not integrating with slack. Slack is connected however, and the slack notification does work when you manually select the slack integration in the drop down, found in the submission in CP. I guess that suggests that when the integration is immediately triggered it works, just not when its added to queue?
- If you do spin up a Fortrabbit instance, make sure its the [Pro Stack](https://www.fortrabbit.com/pricing-pro) not universal. As its the Pro stack that is load balanced. We're then using [workers](https://help.fortrabbit.com/worker-pro) to run the queue as per their advice.

**Comment by engram-design** [comment] 2022-04-13 04:07
Alright, so I've spun up a new Fortrabbit site, with a sample form and Formie (https://formie-test.frb.io/?handle=slack if you're interested).

Submitting that form will create the submission:

![image](https://user-images.githubusercontent.com/1221575/163096585-3455f51a-4d6f-473f-b20b-513ab7c05235.png)

And also create a queue job:

![image](https://user-images.githubusercontent.com/1221575/163096610-824ad946-7a3e-44f4-bb8e-0a270ff05d03.png)

Once I've setup the workers to process the queue, that triggers the queue to run:

![image](https://user-images.githubusercontent.com/1221575/163097796-790dc455-0019-49b5-9f0d-3716752a257f.png)

Which shows the integration ran, and indeed I have a new direct message in Slack 
![image](https://user-images.githubusercontent.com/1221575/163097857-024a992f-1b0b-4ee3-aefb-880b3e23ba97.png)

![image](https://user-images.githubusercontent.com/1221575/163097883-7561f964-4512-4dd9-946b-b82cb388063c.png)

So there doesn't seem to be anything wrong from what I can tell, so it must be related to your form setup? I'm not sure if you have any captchas still enabled, but I would disable them for testing.

Using mutations should be no different from a traditional Twig approach (which is what I'm demo-ing). We still run [onAfterSubmission](https://github.com/verbb/formie/blob/8b0125a9b17c78565e2248be17b1be8b6cd0854d/src/gql/resolvers/mutations/SubmissionResolver.php#L135) which [triggers integrations](https://github.com/verbb/formie/blob/bbadb01ac828bced93b82dc918f31b651e558b3a/src/services/Submissions.php#L141) so long as the submission was a `success` (not spam)

**Comment by engram-design** [comment] 2022-06-08 05:28
Closing due to being unable to reproduce this, even when I've spun up a Fortrabbit site, things are certainly behaving as expected.

If we need to figure a way to debug this further, I'd suggest reaching out on the Craft Discord (`@crawf`) and seeing if I can get access to your production/staging site, as this seems environmental.

**Closed as not planned by engram-design** 2022-06-08 05:28 UTC
