### ISSUE TITLE
Conditional field and page logic, toggling visibility and ability to skip pages

### ISSUE THREAD

**Issue by hongc-cc** [verbb/formie#21] opened 2020-07-26 08:39 UTC
### Description
Is there any plan to implement field / page logic? I checked the roadmap and it seems no. I think this is a critical function for a long form / multi-page form.

**Comment by engram-design** [comment] 2020-07-26 08:41
<s>Conditional logic is a far-off feature (2.0), and we're waiting for Craft 4 to introduce this natively. We don't be implementing our own version of conditional logic in the meantime.</s>

Edit: I take it back - we'll be implementing it ourselves before Craft 4 😄

**Comment by joshuabaker** [comment] 2020-08-04 10:37
@engram-design Craft 4 is a _long_ way out currently, and this is a feature that a good percentage of clients ask us for. I’d love to get us across from Freeform, but I’m not keen on us maintaining different form integrations. Any chance you might reconsider your stance on this?

**Comment by engram-design** [comment] 2020-08-04 10:39
Potentially, but we've got other items of urgency to take care of first. I'll get back in touch with the Craft crew about this to see where it's at. I really want to include this functionality, but on the flip side, really not keen to roll our own, only for a (probably better) implementation available in Craft.

Will keep you posted for sure.

**Comment by russback** [comment] 2020-09-18 11:14
+1 on this - Formie appears to be a nice solution but Freeform currently wins if there are conditional requirements and time/budget is too tight to allow for custom JS behaviour on the site frontend.

**Comment by mattcdavis1** [comment] 2020-10-01 00:29
@engram-design - could we do a minimal event based implementation between now and when full support is added? As far as I can tell, none of the current events allow to return false and disable a field. I think that is all that is needed. I can return an empty string on the rendering event but then I need to add a separate listener to manage validation which is cumbersome.

Even better than an event would be just a simple convention based flag - like if you pass in a variable with the same name as the field handle and it is false then disable the field.

One way or another, i think there should be an interim easy-to-implement solution for conditional rendering of fields.

**Comment by engram-design** [comment] 2020-10-01 00:33
@mattcdavis1 Potentially. I can confirm this will be included in Craft 4, which is pencilled in for availability (likely a beta) around April 2021, so it's really not too far away.

I'll see what we can do in the interim.

**Comment by mattcdavis1** [comment] 2020-10-01 00:39
Maybe a `skips` array at the form level. like:
```
{% do form.setSkips(['handle1', 'handle2']) %}
{% do form.addSkip('handle1') %}
{{ craft.formie.renderForm('someForm', {
  formSkips: ['handle1', 'handle2'],
}) }}
```

**Comment by joshuabaker** [comment] 2020-10-01 14:46
@engram-design It dawned on me that this might actually be two different concerns;
1. Conditional field visibility
1. Workflows (e.g. Skipping to page N)

I know that conditional field visibility is coming in Craft 4 (craftcms/cms#805), but is the latter definitely coming too? I can’t really think of a scenario where Craft would need this as a core feature.

**Comment by engram-design** [comment] 2020-10-01 22:35
For point 2, this will be introduced at the same time we implement survey functionality.

The OP has two feature requests like you've mentioned. Both are not going to be done this year.

**Comment by mark-chief** [comment] 2021-01-05 14:36
Just leaving a note here to add my support for this feature - critical for me to be able to make the jump from freeform - it's just standard request by my clients at the moment. Thanks :)

**Comment by outline4** [comment] 2021-02-22 12:34
Conditional fields or page logic was the first thing a customer of mine was asking for. I didn't even know that it was not possible. This issue seems to come up quite naturally.

**Comment by mariovass** [comment] 2021-03-11 08:48
@engram-design any roadmap for conditional logic ?

**Comment by engram-design** [comment] 2021-03-11 08:51
It's scheduled for 1.4.0, the next minor release. No ETA yet.

**Comment by joshuabaker** [comment] 2021-03-12 14:20
@engram-design Exciting to see that support is coming!

Is there a pre-release to review? Curious to see what it looks like under the hood.

**Comment by engram-design** [comment] 2021-04-20 11:29
Pleased to announce we've finally implemented conditions to fields, pages and page buttons in [1.4.0](https://github.com/verbb/formie/releases/tag/1.4.0)

Check out the [docs](https://verbb.io/craft-plugins/formie/docs/feature-tour/conditions) for a write-up.

**Closed as completed by engram-design** 2021-04-20 11:29 UTC
Labels: feature request

**Comment by joshuabaker** [comment] 2021-04-20 11:31
Amazing news! Excited to give this a go. Thanks, @engram-design.

Dare I ask; Is this hooked up to GraphQL too?

**Comment by engram-design** [comment] 2021-04-20 11:33
@joshuabaker Not at the moment, no, sorry. Purely because I'm not _quite_ sure how to handle that other than providing the conditional rules in queries for you to handle on your end. The joys of headless is that you'll have to manage hiding and showing the fields on the client-side, but Formie can certainly hand you the conditional rules as JSON for you to parse and handle on your end.

Unless you've got any thoughts?

**Comment by joshuabaker** [comment] 2021-04-20 11:40
@engram-design I think it can just be part of the [`FieldInterface`](https://github.com/verbb/formie/blob/0dacc65a49c0558a29e64188687fe5bf18756e3f/src/gql/interfaces/FieldInterface.php#L23) as you say.

```json
{
  "conditions": [
    {
      "field": "firstName",
      "condition": "is",
      "value": "Peter"
    },
    {
      "field": "lastName",
      "condition": "contains",
      "value": "herm"
    },
    {
      "field": "emailAddress",
      "condition": "endsWith",
      "value": "wallaby.com.au"
    }
  ]
}
```

**Comment by joshuabaker** [comment] 2021-04-20 11:49
Regarding actual implementations for frameworks like React and Vue, you might consider supporting/moderating some off-the-shelf projects peripherally. It’d certainly remove friction for license purchases where people want to use with a headless site.

I’ve put together [`react-formie-forms`](https://github.com/joshuabaker/react-formie-forms) based loosely on [Formium](https://formium.io/), which provides a drop-in React component.

```jsx
import {
  defaultComponents,
  Formie,
  submitForm,
} from 'react-formie-forms';

<Formie
  onSubmit={submitForm('/path/to/form/action')}
  validateOnBlur={false}
  components={{
    ...defaultComponents,
    ...myCustomComponents,
  }}
  {...props}
/>
```

Obviously, it’s not trivial to support everything, so having a central place for developers to contribute would be cost beneficial for all.

**Comment by engram-design** [comment] 2021-04-20 22:34
Added in https://github.com/verbb/formie/commit/561751a889169fad583856dd7fe8e55e1d50305a

Note that the `conditions` attribute is a JSON object, and contains more than just a collection of conditions, mostly because it needs to also supply whether it should hide or show the field, and whether it should use `all` or `any` conditions.

As such, you'll probably want to rip [our JS](https://github.com/verbb/formie/blob/craft-3/src/web/assets/frontend/src/js/fields/conditions.js) for conditional parsing in your app, or at least use that as a head-start.

And yep, down the track (probably after 1.5.0), I'll be putting together full guides for a bunch of stuff, like Bootstrap/Tailwind and even Vue/React. I'm no expert on React, but [Formulate](https://vueformulate.com/) for Vue is pretty amazing.

I'll definitely come back to your package - nice work!
