### ISSUE TITLE
Conditions are missing from GraphQL `PageInterface`

### ISSUE THREAD

**Issue by joshuabaker** [verbb/formie#615] opened 2021-10-25 12:40 UTC
## Description

We can currently access field conditions via the [`FieldInterface`](https://github.com/verbb/formie/blob/e4c1126ab3caec5d9bc68f3d776904bc6531a18f/src/gql/interfaces/FieldInterface.php#L185-L194), however, this is missing for the [`PageInterface`](https://github.com/verbb/formie/blob/e4c1126ab3caec5d9bc68f3d776904bc6531a18f/src/gql/interfaces/PageInterface.php).

Please can you add these so that we can reflect conditional logic on the frontend.

The conditions shown in the screenshot below, for example, are currently unavailable to us via a headless SPA.

![local-dandaraliving_8888_cms_formie_forms_edit_21934(iPad Pro)](https://user-images.githubusercontent.com/160484/138696453-19fec7d1-76fd-4533-b515-6d2c103313b4.png)

## Form settings
- Multi-page form: Yes
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: N/a

## Additional info
- Plugin version: 1.4.22
- Craft version: 3.7.17.2
- Multi-site: Yes

Related to #21.

**Comment by engram-design** [comment] 2021-10-25 23:33
Fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.4.22",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment] 2021-10-29 21:27
Fixed in [1.4.23](https://github.com/verbb/formie/releases/tag/1.4.23)

**Closed as completed by engram-design** 2021-10-29 21:27 UTC

**Comment by toddpadwick** [comment] 2021-11-15 15:50
Hi @engram-design we seem to get an internal server error when adding in `pageConditions`, and `id` to our graphql query under pages settings. Works fine with just `enablePageConditions` but obviously there's not much we can do with just the enabled boolean. Id seemed to work fine before updating to 1.4.25.

we're on Formie 1.4.25.

```
fragment FormFragment on Form {
  id
  title
  handle
  siteId
  csrfToken {
    name
    value
  }
  settings {
    displayFormTitle
    displayPageTabs
    displayCurrentPageTitle
    displayPageProgress
    submitMethod
    submitAction
    submitActionTab
    submitActionUrl
    submitActionFormHide
    submitActionMessageHtml
    submitActionMessageTimeout
    redirectUrl
    errorMessageHtml
    loadingIndicator
    loadingIndicatorText
    validationOnSubmit
    validationOnFocus
    defaultLabelPosition
    defaultInstructionsPosition
    progressPosition
    integrations {
      settings
    }
    redirectEntry {
      id
      uri
      slug
      sectionHandle
    }
  }
  pages {
    name
    id
    settings {
      submitButtonLabel
      backButtonLabel
      showBackButton
      buttonsPosition
      pageConditions
      enablePageConditions

    }
    rows {
      fields {
        ...FieldFragment
        ... on Field_Repeater {
          fields {
            ...FieldFragment
          }
        }
        ... on Field_Group {
          fields {
            ...FieldFragment
          }
        }
      }
    }
  }
}
```
![141811297-720a86c3-a280-4d6e-9bcf-d15a79a47f0b](https://user-images.githubusercontent.com/36191462/141812236-9141e3f2-3139-4ce8-97d4-2247cab55803.png)

**Comment by joshuabaker** [comment] 2021-11-15 15:57
@toddpadwick Something else is broken there, I think, unrelated to Formie or this PR.

**Comment by toddpadwick** [comment] 2021-11-15 16:09
Hey @joshuabaker . I've tried stripping down the query to just that page settings and running it in GraphiQL (see below), and I still seem to get internal server errors. Nothing in PHP logs that i can see. 
I can also confirm that pages => `id` no longer exists in the schema since I updated formie. has it been replaced with `uid`? Not that we really need the id but it just demonstrates something might be different since our previous release which was 1.4.12.

![Screenshot 2021-11-15 at 17 06 47](https://user-images.githubusercontent.com/36191462/141814840-c5fec18c-a44e-4560-a9f8-75c7530d1961.png)

**Comment by engram-design** [comment] 2021-11-15 23:33
Are you able to have a look in your logs (either web.log, phperrors.log or formie.log)? If it helps, clearing the logs directory out first, then running the query should give you some sort of insight into the error. `devMode` should be true.

It also goes without saying to clear your caches, including GraphQL caches.

As for the `id` param, that looks like it was made by @andris-sevcenko via https://github.com/verbb/formie/pull/623/commits/a657d3522949dd5a732cd87996ce3439e52782a4#diff-5faca2a3abf2697babb9d433350d698631747d1dc416835c39c0138722fcaf76 - Andris, can you comment on why you did that?

**Comment by engram-design** [comment] 2021-11-15 23:38
@toddpadwick Actually, I can now replicate your error.

![image](https://user-images.githubusercontent.com/1221575/141869480-2f2469e8-c88e-4502-ba96-72ea09e84083.png)

This again seems to be another thing with the PR: https://github.com/verbb/formie/pull/623/commits/a657d3522949dd5a732cd87996ce3439e52782a4#diff-b0bf182da46c2c89ba0911595000ab60abcf1d4ccd6ef8ef5757025fad413ea9

@andris-sevcenko The page conditions aren't a `Type::listOf(Type::string())` but a `Type::string()` because it's a JSON-encoded string. Was there a reason for this change? I note it's also been done on a few other properties like `nextButtonConditions`. 

Does Gatsby do something different?

**Comment by engram-design** [comment] 2021-11-15 23:43
Fixed for the next release. To get this fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.4.25",
  "...": "..."
}
```

Then run `composer update`.

**Comment by andris-sevcenko** [comment] 2021-11-16 07:56
@engram-design @toddpadwick 

The reason for changing `pageConditions` and nextButtonConditions` to a list of strings is because the [default values are empty arrays](https://github.com/verbb/formie/blob/craft-3/src/models/PageSettings.php#L24-L26).

If you query for a form page with those conditions not set to anything, you'll get an error about converting an array to a string. I didn't deep-dive into code back then - I just went by the default value on the model, but now it seems like the best fix would be to set the default value to be `''` instead of `[]`, if it's a JSON _string_.

As for the removal of id/uid fields - I removed them where they did not make sense. Since you have no way of querying pages or page settings in any other way besides going through the form and listing them, there's really no point in having them there at all. 

It's a shame my mind slipped and forgot this would be a breaking change. Also, probably just a nitpick from me and nothing more that can remain. Thankfully, Josh already reverted that!

**Comment by engram-design** [comment] 2021-11-16 08:06
Thanks for the updates @andris-sevcenko and also pushed some changes as you've suggested. As for the `id/uid` there are cases you might want the `id` for a page, which is used on a submission - if you just want to submit one page in a multi-page form, but you weren't to know that! It's correct that you can't query via page ID (maybe you should)

**Comment by toddpadwick** [comment] 2021-11-16 08:17
Hi guys, thanks for solving this so quickly :) 
I'll give `dev-craft-3 as 1.4.25` a go later on today.

**Comment by toddpadwick** [comment] 2021-11-16 10:25
I can confirm that with `dev-craft-3 as 1.4.25` installed, the page `id`, and `enablePageConditions` and `pageConditions` in page settings now work correctly 🙂
