### ISSUE TITLE
Issue with Stripe and calculation field

### ISSUE THREAD

**Issue by Megafry** [verbb/formie#2081] opened 2024-10-07 12:49 UTC
### Describe the bug

Stripe doesn't work if the dynamic value for the payment amount is linked to a calculation field.

fix: after the calculation, the field should dispatch a bubbles input event:
```js
dispatchEvent( new Event("input", { bubbles: !0 }) )
```

### Steps to reproduce

1. Add a field type number.
2. Add a calculation field that multiplies the value from the number field.
3. Add a Stripe payment field.
4. Set the calculation field as the dynamic value.
5. In the frontend, set a value to the number field.
6. The Stripe payment doesn't notice the change from the calculation field.

### Form settings

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: No

### Craft CMS version

5.4.6

### Plugin version

3.0.7

### Multi-site?

No

**Comment by engram-design** [comment] 2024-10-07 22:09
We actually already [do that](https://github.com/verbb/formie/blob/1929aea0dfed02d7aa589742d4751f69844227e6/src/web/assets/frontend/src/js/fields/calculations.js#L161), but the issue is that we're debouncing listening for input events, and that'll be due to the change being triggered for both the source input for the calculations field and the calculations field.

Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-5 as 3.0.7"`.

**Comment by engram-design** [comment] 2024-10-09 09:52
Fixed in [3.0.8](https://github.com/verbb/formie/releases/tag/3.0.8)

**Closed as completed by engram-design** 2024-10-09 09:52 UTC
