### ISSUE TITLE
Integrations triggering on submission

### ISSUE THREAD

**Issue by samuelbirch** [verbb/formie#687] opened 2021-12-10 16:54 UTC
We've setup the Dynamics CRM integration, but it appears that it manually need to be set on each submission for it to work rather than automatically happening on every submission.

**Comment by engram-design** [comment] 2021-12-10 20:09
Integrations will run through Craft's queue system. Can you confirm you're running your queue, either automatically when visiting the control panel, or through the CLI?

**Comment by samuelbirch** [comment] 2021-12-13 09:31
this is the error i'm getting in the logs:

Dynamics integration: API error: “invalid_client
AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application:

**Comment by engram-design** [comment] 2021-12-14 02:28
Can you share the URL that Formie is saying to use as the Redirect URI?

**Comment by samuelbirch** [comment] 2021-12-14 09:32
The url is not in the logs anywhere, but the file the logs are referencing is this:

.../vendor/thenetworg/oauth2-azure/src/Provider/Azure.php:402

it also gives a 504 when refreshing the integration on a form. - I assume its the same issue.

**Comment by engram-design** [comment] 2021-12-14 12:05
What I was referring to was this setting in the CRM settings

![image](https://user-images.githubusercontent.com/1221575/145994018-807b09f6-05d9-4eb8-a5ec-fe657ad9e0f5.png)

And the setting in Azure AD:

![image](https://user-images.githubusercontent.com/1221575/145994988-a561e907-251d-441a-b903-daf4ed949bd8.png)

As that error seems to point that they're different.

**Comment by samuelbirch** [comment] 2021-12-14 13:41
The client has confirmed that the urls are the same.

**Comment by engram-design** [comment] 2021-12-14 19:48
I was going to ask about whether your install has `'usePathInfo' => false` which produces a redirect uri like;

```
https://formie.test/index.php?p=actions/formie/integrations/callback
```

But that's invalid in Azure. It does need to be `https`, so also ensure you're triggering the integration from `https://yoursite.test` **not** `http://yoursite.test` otherwise you'll get this error. 

Azure won't even allow you enter a non-https URL or one that contains a query string.

But what's strange is that this is coming in the logs anyway. If the Redirect URI doesn't match, you should get an error screen like the below during connection:

![image](https://user-images.githubusercontent.com/1221575/146069005-cfd5c601-bdd5-4076-be17-7e24caecc1fb.png)

**Comment by samuelbirch** [comment] 2021-12-15 10:23
usePathInfo is set to true.

The urls are in the correct format (same as your screenshot), its using https. It works to connect to dynamics when first setup, it feels like its an issue with refreshing the token?

**Comment by engram-design** [comment] 2021-12-15 10:48
Ah I see, yes you mentioned refreshing the integration, which would be using the refresh token. I'll look at replicating that...

**Comment by engram-design** [comment] 2021-12-15 20:03
Looks like I can replicate this as well now, definitely something to do with the refresh token after it's expired.

**EDIT** Actually, I take that back. I just realised I was on the `http` version of the project, and switching to `https` (when editing the forms integration settings) works when you hit the "Refresh Integration" button.

**Comment by samuelbirch** [comment] 2021-12-15 20:26
Is there more logging or something we can add in to try and get a more detailed error messages? - like the actually url it says it has an issue with?

**Comment by engram-design** [comment] 2021-12-16 00:34
Looking into a way we can add this into Formie, but is it all a bit caught up in the `league/oauth` package. But if you're adventurous - you can add the following:

```
$params   = $grant->prepareRequestParameters($params, $options);

file_put_contents('formie-oauth.txt', print_r($params, true), FILE_APPEND);

$request  = $this->getAccessTokenRequest($params);
```

At line https://github.com/thephpleague/oauth2-client/blob/master/src/Provider/AbstractProvider.php#L536 which should dump the details it's using for the access token request to a file in `web/formie-oauth.txt`.

Looking if I can make this a bit more user-friendly.

**Comment by samuelbirch** [comment] 2021-12-16 11:37
The refresh integration is failing with a 504, looking at it further its returning a "allowed memory size... " issue. Its not getting stuck in a loop is it? - the getClient() method triggering a request which in return calls the getClient() etc.

**Comment by engram-design** [comment] 2021-12-16 11:45
After just adding the above line? (note I included the before and after lines for reference - don't include them twice). 

I have also pushed an update that includes log information which might help if you don't want to poke around the code.

And while it does indeed try to make a GET request in the `getClient()` method, it shouldn't be recursive (we memoize using `$this->_client` so next time it's called, we return the client). If it fails with 401, it's likely an invalid token, and we proceed to refresh, and update the memoized client.

**Comment by samuelbirch** [comment] 2021-12-16 11:53
I only added the file_put_contents line :)

The "refresh integration" is constantly failing with a 504, but when i manually try to push a submission to the dynamics integration i'm getting this error:

```
Dynamics integration: API error: “{"error":{"code":"0x0","message":"An error occurred while validating input parameters: Microsoft.OData.ODataException: An undeclared property 'new_sectors' which only has property annotations in the payload but no property value was found in the payload. In OData, only declared navigation properties and declared named streams can be represented as properties without values.\r\n   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadUndeclaredProperty(IODataJsonLightReaderResourceState resourceState, String propertyName, Boolean propertyWithValue)\r\n   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadPropertyWithoutValue(IODataJsonLightReaderResourceState resourceState, String propertyName)\r\n   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.<>c__DisplayClass9_0.b__0(PropertyParsingResult propertyParsingResult, String propertyName)\r\n   at Microsoft.OData.JsonLight.ODataJsonLightDeserializer.ProcessProperty(PropertyAndAnnotationCollector propertyAndAnnotationCollector, Func`2 readPropertyAnnotationValue, Action`2 handleProperty)\r\n   at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadResourceContent(IODataJsonLightReaderResourceState resourceState)\r\n   at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadNextNestedInfo()\r\n   at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadAtNestedResourceInfoEndImplementation()\r\n   at Microsoft.OData.ODataReaderCore.ReadImplementation()\r\n   at Microsoft.OData.ODataReaderCore.InterceptException[T](Func`1 action)\r\n   at System.Web.OData.Formatter.Deserialization.ODataReaderExtensions.ReadResourceOrResourceSet(ODataReader reader)\r\n   at System.Web.OData.Formatter.Deserialization.ODataResourceDeserializer.Read(ODataMessageReader messageReader, Type type, ODataDeserializerContext readContext)\r\n   at System.Web.OData.Formatter.ODataMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger)"}}”
```

**Comment by engram-design** [comment] 2021-12-16 12:05
What PHP version are you running? I don't think it'd be a difference, but just in case.

Not seen that error to date - but likely because you haven't been able to setup the mapping yet? I'm not sure if `new_sectors` is a field in your form, or a field in your Dynamics object?

Maybe if you're able to send your database to `web at verbb.io` it's hopefully something I can replicate? Understand if you're unable to share it though.

**Comment by samuelbirch** [comment] 2021-12-16 12:10
I'm running php@7.4

The client can connect when first setting it up, and can do all the mappings. Its just when a submission was tested it was failing in the queue, then if i try a manual push or the refresh thats when the errors start. It does free very much like a refreshing token problem.

I'll ask if the are happy to share a db.

**Comment by engram-design** [comment] 2021-12-16 12:13
Yep, agreed that seems the be the issue, and same PHP version. I'm not sure how it could create a recursive error (causing a 504 error), but I must clearly be missing something.

One thing to test it the logging added in https://github.com/verbb/formie/commit/33c6d3db563a9582214b336aff2636b906b13c10 which will remove the need for the `file_put_contents` - but sounds like something else is going on...

**Comment by samuelbirch** [comment] 2021-12-16 13:19
i'm getting this error with latest dev-craft-3 branch:

`API error: “Cannot access protected property TheNetworg\OAuth2\Client\Provider\Azure::$clientId” .../vendor/verbb/formie/src/services/Tokens.php:214`

EDIT: i think the logging code you added should be $integration->clientId etc instead of $provider->clientId.

**Comment by samuelbirch** [comment] 2021-12-16 13:47
Tokens seem to be refreshing ok. - thats not what is causing the issues :(

**Comment by samuelbirch** [comment] 2021-12-16 13:51
I think the issue with the submissions not pushing through to Dynamics is that the schema names may have changed (according to what i've read) - but i can't check update them using the refresh integration button as that is throwing a 504.

If we can get that sorted we may be in a place where it could be working!

**Comment by engram-design** [comment] 2021-12-17 03:39
Yeah, sorry about that logging, I should've double checked that, using protected properties. Should be fixed now, but sounds like that's refreshing properly.

I'm not sure what to think of the 504 error, seemingly caused by an infinite loop. Having said that, it _does_ take a reasonable amount of time to fetch all the content, just due to how their API works, so I'm wondering if it might just be hitting some resource limits. It does take a good 10 seconds to refresh on my local install, as it's trying to fetch custom fields and object attributes.

Worth a shot at commenting out some of the lines here, to see if that makes a difference. https://github.com/verbb/formie/blob/4aee7ade7700dc910352b9c8b3b0b9e71fe188fb/src/integrations/crm/MicrosoftDynamics365.php#L165-L168

**Comment by samuelbirch** [comment] 2021-12-17 09:30
I think my 504 issues is because there is so much data in this integration and like you say their api seems to be quite slow. Increasing my nginx timeout limit solved that issue and the other one with the submissions not sending looks to be to be a data issue (client fields setup etc).

Thanks for all your help on this!

**Comment by engram-design** [comment] 2021-12-17 11:14
Aha, glad you got to the bottom of it. Thanks for your persistence on this issue, I know it’s taken a while to get there.

Let’s keep an eye on things and I’ll see what I can do about performance.

**Closed as completed by engram-design** 2021-12-17 11:14 UTC
