### ISSUE TITLE
Cann't update formie since 1.2.28 (Composer Error)

### ISSUE THREAD

**Issue by lexislav** [verbb/formie#234] opened 2020-11-25 09:14 UTC
Cann't update formie – getting composer error:
This happens sice 1.2.28, the Composer Error is from atest 1.3.0

```Composer: Package "craftcms/vue-asset" listed for update is not installed. Ignoring.
Package "yiisoft/yii2-shell" listed for update is not installed. Ignoring.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

Problem 1
- don't install fakerphp/faker v1.9.1|remove fzaninotto/faker v1.9.1
- don't install fakerphp/faker v1.9.1|don't install fzaninotto/faker v1.9.1
- don't install fakerphp/faker v1.9.1|don't install fzaninotto/faker v1.9.1
- verbb/formie 1.3.0 requires fakerphp/faker 1.9.1 -> satisfiable by fakerphp/faker[v1.9.1].
- Installation request for verbb/formie 1.3.0 -> satisfiable by verbb/formie[1.3.0].
- Installation request for fzaninotto/faker (locked at v1.9.1) -> satisfiable by fzaninotto/faker[v1.9.1].

Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.```

**Comment by engram-design** [comment] 2020-11-25 09:39
Duplicate of https://github.com/verbb/formie/issues/224 and https://github.com/verbb/formie/issues/223

**Closed as completed by engram-design** 2020-11-25 09:39 UTC
