### ISSUE TITLE
Agree field: description is marked as requried via asterisk but is not really required

### ISSUE THREAD

**Issue by tremby** [verbb/formie#1501] opened 2023-07-17 20:13 UTC
### Describe the bug

Label and description for agree fields are both marked with an asterisk as if they're required, but description is not really required.

![screen](https://github.com/verbb/formie/assets/199635/8550f4fd-5286-45c4-9123-aebb1b4e9d07)

What I actually want to do is have an agree checkbox with text next to it (which I'd definitely mark up as a `<label>` if I had the choice) but I do not want more text above it, so I am in fact happy with the description field *not* being required -- I'm using Craft headless and building my own UI so I can check for the case where there's a label but no description, and render the label next to the checkbox in that instance. But this ticket is just about the confusing UI.

### Steps to reproduce

1. Add an "agree" field
2. Look at its "general" tab, see the asterisk next to "description"
3. Enter label but not description
4. "Apply"
5. Note that "description" was not really required

### Form settings

- Multi-page form: n/a
- Submission Method: n/a
- Client-side Validation: n/a
- Custom Form Templates: n/a

### Craft CMS version

4.4.14

### Plugin version

2.0.32

### Multi-site?

yes

**Comment by engram-design** [comment] 2023-07-21 12:47
So a description _should_ be required, and I reckon that's just down to how even a blank rich text field actually has some (ProseMirror schema) content. I'll fix that up. Sorry to say, but this will remain required, as while it might not be required on your end, it gives users the flexibility to define the label of the field, and the text alongside the checkbox. I'm aware that may seem redundant for your needs, but I know for a fact people like to have the option for that!

**Comment by tremby** [comment] 2023-07-21 20:50
> but I know for a fact people like to have the option for that!

"Option" sounds optional...

This field type is always just a single checkbox. Why require *two* pieces of text for it?

Why not make the one which says it'll appear above optional?

**Comment by engram-design** [comment] 2023-07-21 21:26
It's probably more an internal complication than anything. The `label` for a field has limited length when stored in the database, as we inherit from Craft's own base field. Fields are stored in the `fields` database table, so the same restrictions of custom fields you create in Craft apply for Formie fields.

Secondly, people want to be able to add formatting to the label, which has to be another attribute of a field.

So while annoying, there will probably always be two bits of content for an Agree field, because we can't have rich text content for the field label. It's true that we could go the other way and auto-generate the label (and have it hidden) based on something random (like Section and a few other fields), but that just seemed to overcomplicate things when people want to have both a label and a description.

**Comment by tremby** [comment] 2023-07-21 21:35
The way I see it:

- If the user fills in both, nothing needs to change.
- Keep the "description" required as you say you want to -- this definitely keeps the UI intuitive (so the one which says "this appears next to the checkbox" does exactly that, and I agree that something does need to go next to the checkbox).
- In this special case of the "agree" field, make the "label" optional in the admin UI.
- If the "label" field is left empty by the user, and Craft internals demand it to have something, add some token which internally to Formie means "empty". Or if you can store it empty, go ahead.
- Look for that token (or it being empty) when displaying the admin panel, and render an empty field.
- Look for that token (or it being empty) when displaying the UI, and
  - if it's not to be empty, business as usual
  - if it's to be empty, render nothing above the checkbox. If in the normal case that is the `<label>` (I haven't looked at the Formie UI), instead wrap the checkbox and description (or just the description) in `<label>`.

**Comment by tremby** [comment] 2023-07-21 21:36
Or are we talking about something which is not the user-readable label? Are you maybe talking about the field handle (`name` attribute)?

**Comment by engram-design** [comment] 2023-07-21 21:58
So that all makes sense. The `name` and `label` are the same thing where a field is considered.

**Comment by LoriWJ** [comment] 2023-08-29 11:23
The issue here is that the "Description" field looks like it's required, but it isn't. Either the asterisk in the label needs to be removed or the field needs to be changed so it's actually required. We came across this issue because our custom field stopped working when the description field was left empty. We have fixed our custom field template, but this is unexpected behaviour.

**Comment by engram-design** [comment] 2023-08-30 05:22
Fixed for the next release. To get this early, run `composer require verbb/formie:"dev-craft-4 as 2.0.34.1"`.

**Comment by engram-design** [comment] 2023-08-30 23:12
Fixed in [2.0.35](https://github.com/verbb/formie/releases/tag/2.0.35)

**Closed as completed by engram-design** 2023-08-30 23:12 UTC

**Comment by tremby** [comment] 2023-08-30 23:17
Thanks for addressing this.

Is the text which displays *above* the checkbox still required, or is that now optional?

**Comment by engram-design** [comment] 2023-08-30 23:19
It's still required - at least for the short-term future. You'll need to supply a Label and Description.

**Comment by tremby** [comment] 2023-08-30 23:23
OK. For now I'll keep my scheme of treating a `_` in that field as "empty" (which I can do since I have a totally separate UI implementation). I'll open a separate feature request to make it optional.
