### ISSUE TITLE
Conditional Form Support

### ISSUE THREAD

**Issue by edhebert** [verbb/formie#334] opened 2021-02-03 02:13 UTC
**What are you trying to do?**
A description of what you want to happen.

Display certain fields/labels depending on a user's previous selection.

**What's your proposed solution?**
A description of how you think this could be solved, including any alternatives that you considered.

Some sort of if/else behavior based on selections from a dropdown or radio field.

**Additional context**

**Comment by engram-design** [comment] 2021-02-03 03:45
Duplicate of https://github.com/verbb/formie/issues/21

**Closed as completed by engram-design** 2021-02-03 03:45 UTC
Labels: feature request
