### ISSUE TITLE
Primary site translation in description field issue

### ISSUE THREAD

**Issue by TomDeSmet** [verbb/formie#320] opened 2021-01-26 11:07 UTC
**Description**
Very strange:
I have an agree field with a description I translate using static translations in `formie.php`.
The default site is NL, but if I have **no** translation for NL or I put something like this:
`"Ik schrijf me in voor de nieuwsbrief" => "Ik schrijf me in voor de nieuwsbrief"`
the translation falls back to English which is the second site in the Sites list.

If I change it to anything else than 2 exactly the same strings such as:
`"Ik schrijf me in voor de nieuwsbrief" => "test"` 
or 
`"Ik schrijf me in voor de nieuwsbrief" => "Ik schrijf me in voor de nieuwsbrief "` (mind the extra space at the end)
it works as it should.

**Comment by engram-design** [comment] 2021-01-26 11:48
That seems odd. If you're only the NL site, it shouldn't be grabbing the English version of anything.

For clarity, what have you got in the Agree field in the control panel - the source string that you then translate for each site?

**Comment by TomDeSmet** [comment] 2021-01-26 12:10
Just the one I showed above: Ik schrijf me in voor de nieuwsbrief`
Nothing fancy. It works for all the other languges.

**Comment by engram-design** [comment] 2021-01-26 23:23
Should be fixed in the next release. To get the fix early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.3.13",
  "...": "..."
}
```

Then run `composer update`.

Please note however that this static translation has been moved to `site.php`, where it should've been in the first place. `site.php` should be where translations for content, or front-end stuff, and `formie.php` should be for anything in the control panel. Regarding this, let me know if you come across any inconsistencies as I'll be doing an audit.

**Comment by engram-design** [comment] 2021-01-28 02:07
Fixed in [1.3.14](https://github.com/verbb/formie/releases/tag/1.3.14)

**Closed as completed by engram-design** 2021-01-28 02:07 UTC

**Comment by frontedbe** [comment] 2023-07-11 09:41
Hi @engram-design Could it be that since the 2.0.0 release where you state that "_All front-end static translations now use only the formie category. If you're using static translation to translate any text for front-end forms, ensure you move any of these translations in your site.php or app.php files into formie.php._" I am now experiencing the same issue as @TomDeSmet in Craft 4.4.15 and Formie 2.0.33?

**Comment by engram-design** [comment] 2023-07-11 14:01
I can confirm everything has been moved to `formie.php` for translations.

So Is your issue translating the Agree field description?

**Comment by frontedbe** [comment] 2023-07-11 14:05
No I don't have an Agree field present. Issue is the translation of a label or placeholder of a field that's defined in the form builder, it defaults to the translation of another site, exactly the problem that @TomDeSmet describes in his first post at the top of this page :)

**Comment by engram-design** [comment] 2023-07-12 04:09
So the only way I can replicate that is if I set a value for the primary site's static translation. If you can maybe confirm your setup with mine below?

Field Label `Your Name` (a name field - the field type doesn't matter though).

- Site A (English - primary)
- Site B (German)
- Site C (French)

Translations files are:

**translations/de/formie.php**
```php
<?php

return [
    'Your Name' => 'Your German Name',
];
 ```

**translations/en/formie.php**
```php
<?php

return [
    'Your Name' => 'Your English Name',
];
 ```

**translations/fr/formie.php**
```php
<?php

return [
    'Your Name' => 'Your French Name',
];
 ```

Viewing Site B/C, if I comment out the French and German translations, it'll fallback to the English translation (`Your English Name`), despite this being on non-English sites. If I comment out the English translation then it falls back to the label defined at the field `Your Name`.

I assume you want the French/German sites to show `Your Name` and not `Your English Name`, which does make sense. Although I'm not sure that's how static translations work with Craft.
