### ISSUE TITLE
GraphQL submission : recaptcha is not checked

### ISSUE THREAD

**Issue by klevron** [verbb/formie#669] opened 2021-12-02 10:57 UTC
**Description**
I'm trying to use reCaptcha in a headless/graphql configuration. I don't send `g-recaptcha-response` for the moment, but I can create submissions, it looks like recaptcha is not checked when using graphql mutation.

**Steps to reproduce**
1. Create a form and enable recaptcha
2. Send a GraphQL mutation without `g-recaptcha-response`

### Form settings

- Multi-page form: Yes
- Submission Method: Page Reload
- Client-side Validation: Yes
- Custom Form Templates: No

**Additional info**
- Plugin version: dev-craft-3
- Craft version: 3.7.20
- Multi-site: No

**Comment by engram-design** [comment] 2021-12-02 12:12
We do captchas checks for GQL mutations https://github.com/verbb/formie/blob/craft-3/src/gql/resolvers/mutations/SubmissionResolver.php#L114-L123 and anything that's flagged as spam is marked as spam.

Is the submission going through and **not** being marked as spam? Is reCAPTCHA enabled on the form?

**Comment by klevron** [comment] 2021-12-02 13:32
> Is the submission going through and **not** being marked as spam? Is reCAPTCHA enabled on the form?

Yes and yes.

Here is what I get in `form.settings.integrations` :

```
{
    "handle": "recaptcha",
    "secretKey": "###",
    "siteKey": "###",
    "type": "v3",
    "size": "normal",
    "theme": "light",
    "badge": "bottomright",
    "language": "en",
    "minScore": "0.5",
    "showAllPages": "1",
    "spamReason": null,
    "name": null,
    "enabled": "1",
    "sortOrder": null,
    "cache": [],
    "tokenId": null,
    "uid": null,
    "referrer": "",
    "id": null,
    "dateCreated": null,
    "dateUpdated": null
}
```

Here is the mutation request payload (without `g-recaptcha-response`) :

```
{
    "operationName": "FormMutation",
    "variables": {
        "yourName": {
            "firstName": "test",
            "lastName": "test"
        },
        "emailAddress": "",
        "message": "test",
        "text": "test",
        "text2": ""
    },
    "query": "mutation FormMutation($yourName: testForm_yourName_FormieNameInput, $emailAddress: String, $message: String, $text: String, $text2: String) {\n  save_testForm_Submission(\n    yourName: $yourName\n    emailAddress: $emailAddress\n    message: $message\n    text: $text\n    text2: $text2\n  ) {\n    id\n    __typename\n  }\n}\n"
}
```

**Comment by klevron** [comment] 2021-12-02 13:34
I tried with another form, with just one field, and it works !
Recaptcha settings are the same on the 2 forms, I don't understand...

**Comment by engram-design** [comment] 2021-12-02 19:43
Hmm, that does seem odd, and I can't reproduce it with a bunch of different forms (new and existing). I'll see what might be happening...

**Comment by klevron** [comment] 2021-12-03 08:34
I find a way to reproduce this issue : 

- create a form with recaptcha and 2 pages :

  - page 1 with text field
  - page 2 with a condition on text field

![image](https://user-images.githubusercontent.com/4560725/144570777-8a35199d-e426-4022-9726-95d7d971fa73.png)

Recaptcha won't be checked on gql mutation, submission won't be in spam.

**Comment by engram-design** [comment] 2021-12-03 22:47
That's a good point - technically this will be the same issue for a traditional form, not just for GQL mutations.

I'm not quite sure how to handle this scenario - or if it can be handled at all. I would encourage people not to construct their forms this way if it can be helped.

Otherwise, we have to conditionally render the captcha on the (actual) last page or the conditionally-visible last page, which isn't great behaviour, and likely prone to issues.

**Comment by engram-design** [comment] 2022-06-08 05:06
Captcha support for GraphQL was added via https://github.com/verbb/formie/issues/794

**Closed as completed by engram-design** 2022-06-08 05:06 UTC
