### ISSUE TITLE
"Action on Submit": Redirect to Entry: Should respect Language / Site

### ISSUE THREAD

**Issue by adrianjean** [verbb/formie#1001] opened 2022-07-25 18:00 UTC
### Describe the bug

My site is bilingual, and I have a form upon which I have set the "Action on submit" to redirect to an entry. 

However it seems the page redirect does not take into account the form user's current site — seems as tho Formie saves the specific entry, and not the translatable entry. 

### Steps to reproduce

1. On a multi-lingual site, set the "Action on submit" on a form to "Redirect to an entry"
2. Select an entry in one language.
3. Visit the form in another language and fill out the form and submit
4. Note that the entry you are redirected to is not in the originating language of the form.

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

3.7.48

### Plugin version

1.6.4

### Multi-site?

Yes

**Comment by engram-design** [comment] 2022-07-25 22:45
Duplicate of https://github.com/verbb/formie/issues/706 and on the list to fix!

**Closed as completed by engram-design** 2022-07-25 22:45 UTC
