### ISSUE TITLE
Redirect on submit goes to Default language

### ISSUE THREAD

**Issue by torgeirbeyer** [verbb/formie#970] opened 2022-07-05 10:07 UTC
**Description**
We have a form that should redirect to a translated version of a page on submit, but it redirects to the Default language.

**Steps to reproduce**
1. Create a form and include on a translated entry page
2. Redirect to translated version of a Thank you page
3. Save and submit form
4. User is sent to the Default language version of the Thank you page

### Form settings
Please pick from the options below.

- Multi-page form: No
- Submission Method: Ajax
- Client-side Validation: Yes
- Custom Form Templates: Yes

**Additional info**
- Plugin version: 1.5.9
- Craft version: 3.7.37
- Multi-site: Yes
**Additional context**

**Comment by engram-design** [comment] 2022-07-05 10:31
Duplicate of https://github.com/verbb/formie/issues/706 and refer to https://github.com/verbb/formie/issues/693#issuecomment-997786282 for a short-term solution.

**Closed as completed by engram-design** 2022-07-05 10:31 UTC
