### ISSUE TITLE
Submission status on element index not correct

### ISSUE THREAD

**Issue by JeanLucEsser** [verbb/formie#1075] opened 2022-09-05 07:58 UTC
### Describe the bug

Whatever the status I choose for a submission, the element index always shows the green dot.

<img width="369" alt="image" src="https://user-images.githubusercontent.com/14908712/188398059-23befdef-1a32-48bc-8393-2e87ff3066bd.png">

<img width="925" alt="image" src="https://user-images.githubusercontent.com/14908712/188398147-f6be97c8-9154-4c12-b080-71ea51a12ed0.png">

### Steps to reproduce

1. Create some statuses
2. Change the status on an existing submission
3. The status is saved but not shown on the element index

### Form settings

- Multi-page form: No
- Submission Method: Page Reload
- Client-side Validation: No
- Custom Form Templates: No

### Craft CMS version

4.2.3

### Plugin version

2.0.9

### Multi-site?

No

**Comment by engram-design** [comment] 2022-09-05 08:32
Duplicate of https://github.com/verbb/formie/issues/1049

**Closed as completed by engram-design** 2022-09-05 08:32 UTC
